docs_dir: ./pages
site_name: Frontend Experience Docs

markdown_extensions:
  - toc:
      permalink: "#"

nav:
- Home: index.md
- Onboarding:
  - Video recordings: onboarding/recordings.md
  - PR template: onboarding/pr-template.md
  - Platform styling: onboarding/platform-styling.md
- Testing:
  - Testing strategy: testing/testing-strategy.md
- Frontend migrations:
  - Frontend compoonents 3 => 4: frontend-migrations/frontend-components-3-to-4.md
  - Frontend compoonents to PatternFly component groups: frontend-migrations/frontend-components-to-PF-component-groups.md
  - PatternFly 4 => 5: frontend-migrations/pf-4-to-pf5.md
  - React Router DOM 5 => 6: frontend-migrations/react-router-dom-v5-to-v6.md
- Services:
- Payload tracker UI: pages/services/Payload tracker UI.md
- PF Component groups: pages/services/PF Component groups.md
- Landing page UI: pages/services/Landing page UI.md
- PF Data view: pages/services/PF Data view.md
- Frontend components: pages/services/Frontend components.md
- Notifications UI: pages/services/Notifications UI.md
- Learning resource page: pages/services/Learning resource page.md
- UI starter app: pages/services/UI starter app.md
- User preferences UI: pages/services/User preferences UI.md
- RBAC UI: pages/services/RBAC UI.md
- Sources UI: pages/services/Sources UI.md
- PF Virtual assistant: pages/services/PF Virtual assistant.md
- API catalog: pages/services/API catalog.md
- Settings UI: pages/services/Settings UI.md

