docs_dir: ./pages
site_name: Frontend Experience Docs

markdown_extensions:
  - toc:
      permalink: "#"

nav:
- Home: index.md
- Onboarding:
  - Video recordings: onboarding/recordings.md
  - PR template: onboarding/pr-template.md
  - Platform styling: onboarding/platform-styling.md
- Testing:
  - Testing strategy: testing/testing-strategy.md
# when making changes to "Services:" subitems, please also edit the update_services.sh script
- Services:
  - Landing page UI: services/Landing page UI.md
  - Settings UI: services/Settings UI.md
  - User preferences UI: services/User preferences UI.md
  - API catalog: services/API catalog.md
  - Notifications UI: services/Notifications UI.md
  - RBAC UI: services/RBAC UI.md
  - Sources UI: services/Sources UI.md
  - Learning resource page: services/Learning resource page.md
  - Payload tracker UI: services/Payload tracker UI.md
  - UI starter app: 
      - Overview: services/UI starter app.md
      - 'Frontend Operator':
        - Overview: services/UI_starter_app/frontend-operator/index.md
        - 'Basic configuration': services/UI_starter_app/frontend-operator/basic-configuration.md
        - 'UI module configuration': services/UI_starter_app/frontend-operator/modules.md
        - Navigation: services/UI_starter_app/frontend-operator/navigation.md
        - 'Services dropdown': services/UI_starter_app/frontend-operator/services.md
        - Search: services/UI_starter_app/frontend-operator/search.md
  - Frontend components: services/Frontend components.md
  - PF Component groups: services/PF Component groups.md
  - PF Data view: services/PF Data view.md
  - PF Virtual assistant: services/PF Virtual assistant.md
- Frontend migrations:
  - Frontend components 3 => 4: frontend-migrations/frontend-components-3-to-4.md
  - Frontend components to PatternFly component groups: frontend-migrations/frontend-components-to-PF-component-groups.md
  - PatternFly 4 => 5: frontend-migrations/pf-4-to-pf5.md
  - React Router DOM 5 => 6: frontend-migrations/react-router-dom-v5-to-v6.md


