docs_dir: ./pages
site_name: Frontend Experience Docs

markdown_extensions:
  - toc:
      permalink: "#"

nav:
- Home: index.md
- Testing strategy: testing-strategy.md
- Video recordings: recordings.md
- PR template: pr-template.md

