name: Update services docs

on:
  # run every day at 1 AM
  schedule:
    - cron: '0 1 * * *'
  # allow manual triggering
  workflow_dispatch:

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: sudo apt-get install git

      - name: Make the update script executable
        run: chmod +x update_services.sh

      - name: Run the update_docs.sh script
        run: ./update_services.sh

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="update-services-docs-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Update services with latest READMEs" || echo "No changes to commit"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH_NAME
          title: "Update Services in docs"
          body: "Update of the Services docs section with the latest README changes."
          labels: |
            documentation
